dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
language: node_js
node_js: "stable"
before_install:
  - stty cols 80
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
install: npm ci
script: npm run validate
after_success: npx semantic-release
branches:
  only:
    - master
    - next
    - beta
