dist: trusty
sudo: required
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta fluxbox
before_install:
  - stty cols 80
  - apt-get install gconf-service
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
language: node_js
cache:
  directories:
    - "~/.npm"
notifications:
  email: false
node_js: "stable"
install: npm ci
script: npm run validate
after_success: npx semantic-release
branches:
  only:
    - master
    - next
