name: End-to-End Tests
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: '${{ matrix.os }} node ${{ matrix.node }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - run: npm ci
      - run: npm run validate
      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chrome tests/testcafe'
      - run: npx semantic-release
        if: github.ref == 'master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
